rest-gateway {
  host = "0.0.0.0"
  host = ${?REST_GATEWAY_HOST}
  port = 7070
  port = ${?REST_GATEWAY_PORT}
  hard-termination-deadline = 10.seconds
  hard-termination-deadline = ${?REST_GATEWAY_HARD_TERMINATION_DEADLINE}
}

openapi {
  enabled = true
  enabled = ${?OPENAPI_ENABLED}
  specs-folder = "specs"
  specs-folder = ${?OPENAPI_SPECS_FOLDER}
}
